name: Cron Job

on:
  schedule:
    # Rodar todos os dias às 3:00 UTC (0:00 horário de Brasília)
    - cron: '00 00 * * *'

jobs:
  run-cron-job:
    if: ${{github.event_name == 'schedule'}}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a script
      run: echo "Running the scheduled task"
