name: Cron Job Template

on:
  schedule:
    # Rodar todos os dias às 15:00 UTC (12:00 horário de Brasília)
    - cron: '00 15 * * *'

jobs:
  run-cron-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a script
      run: echo "Running the scheduled task"
