# Nome do Workflow
name: GitHub Actions - Matrix strategy Template

# Nome para a execução
run-name: Running - Web testing - ${{ github.event_name }}
on:
  push:
    branches:
    - develop
jobs:
  on-push-test-page-object-web-testing:
    if: ${{ github.event_name == 'push' }}
    # máquina que será gerada
    runs-on: ubuntu-20.04
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        tags: [CT1, CT2]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Node.js 19.1
        uses: actions/setup-node@v3
        with:
          node-version: '19.1'

      - name: Install Requirements
        run: |
            python -m pip install --upgrade pip
            pip install -U -r requirements.txt
            sudo npm install @playwright/test
            sudo npx playwright install-deps
            rfbrowser init

      - name: Running testes
        run: |
          robot -d ./results -v HEADLESS:true -v BROWSER:${{matrix.browser}} -i ${{matrix.tags}} tests/teste_com_page_object.robot
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results-${{matrix.browser}}
          path: ./results
          if-no-files-found: ignore
          retention-days: 2